<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MBD2ILJ" name="com.guru99.keywordDrivenFramework.NewTest" tests="9" failures="0" timestamp="29 Aug 2019 00:52:51 GMT" time="8.110" errors="1">
  <testcase name="testData" time="4.567" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.186" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.912" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.246" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="1.473" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.399" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.008" classname="com.guru99.keywordDrivenFramework.NewTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.guru99.keywordDrivenFramework.NewTest.testData(NewTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testData -->
  <testcase name="testData" time="0.134" classname="com.guru99.keywordDrivenFramework.NewTest"/>
  <testcase name="testData" time="0.185" classname="com.guru99.keywordDrivenFramework.NewTest"/>
</testsuite> <!-- com.guru99.keywordDrivenFramework.NewTest -->
